module.exports = {
  'function-blacklist': null,
  'function-calc-no-unspaced-operator': true,
  'function-comma-newline-after': 'always-multi-line',
  'function-comma-newline-before': null,
  'function-comma-space-after': 'always-single-line',
  'function-comma-space-before': 'never',
  'function-linear-gradient-no-nonstandard-direction': true,
  'function-max-empty-lines': 0,
  'function-name-case': 'lower',
  'function-parentheses-newline-inside': 'always-multi-line',
  'function-parentheses-space-inside': 'never-single-line',
  'function-url-no-scheme-relative': true,
  'function-url-quotes': 'always',
  'function-url-scheme-blacklist': null,
  'function-url-scheme-whitelist': null,
  'function-whitelist': [
    'alpha',
    'blur',
    'calc',
    'ceil',
    'darken',
    'floor',
    'linear-gradient',
    'media',
    'rotateZ',
    'round',
    'scale',
    'translate3d',
    'translateX',
    'translateY',
    'url',
  ],
  'function-whitespace-after': 'always',
};
